export const animationConfig = {
  loader: {
    minimumMs: 3000,
    bloomDuration: 0.9,
    bloomStagger: 0.13,
    bloomRotation: 18,
    spinDuration: 1.35,
    loadingPulseDuration: 0.65,
    companyRevealDuration: 0.65,
    companyWordStagger: 0.08,
    breatheDuration: 2.6,
    breatheScale: 1.025,
    hintDuration: 0.6,
  },
  intro: {
    petalStart: 0.08,
    petalTravelStagger: 0.14,
    logoTravelDuration: 1.55,
    logoHandoffDuration: 0.08,
    logoHandoffStart: 2.24,
    overlayFadeStart: 0.1,
    overlayFadeDuration: 0.82,
    navStart: 2.34,
    navDuration: 0.5,
    navItemStagger: 0.07,
    heroStart: 1.25,
    heroLineDuration: 0.3,
    heroLineStagger: 0.08,
  },
  smoothScroll: {
    duration: 1.15,
  },
  ambient: {
    blobDurationSeconds: 18,
  },
  video: {
    introStart: 0.46,
    fadeDuration: 1.05,
    loop: false,
    objectPositionDesktop: '52% 42%',
    objectPositionMobile: '50% 40%',
    mobileBreakpoint: 980,
    endFrameOffsetSeconds: 0.05,
    intersectionThreshold: 0.08,
  },
  glass: {
    cardRevealStart: 0.92,
    cardRevealDuration: 0.72,
    cardRadius: 28,
    buttonRadius: 999,
  },
  videoFrame: {
    radius: 28,
    revealStart: 0.38,
    revealDuration: 1.05,
  },
  aiChat: {
    revealStart: 2.28,
    revealDuration: 0.78,
  },
  videoBleed: {
    left: '5.5rem',
    right: '2.5rem',
    top: '2.25rem',
    bottom: '2.5rem',
    strength: 1.05,
    divCount: 5,
  },
  ease: {
    soft: 'power3.out',
    inOut: 'power2.inOut',
    linear: 'none',
  },
} as const
